### ISSUE TITLE
Implementations

### ISSUE THREAD

**Issue by K1H1** [htl-perg-2019-20-5ahif/contact-list-exercise-K1H1#1]
Hi @rstropek,
I implemented all requirements that are specified in the swagger- file.

Greetings,
Katrin Haslinger

**Comment by rstropek** [comment]
Don't check in unnecessary files (e.g. *.vscode*, *bin*, *obj*).

**Comment by rstropek** [comment]
I recognized two things when looking through your code:

* Use `string.IsNullOrEmpty` instead of `myString == null || myString.Length == 0`
* Format your code before checking it in

Otherwise, well done. The extra point is yours.

Greetings,
Rainer Stropek
